// Generated by CoffeeScript 1.3.3
(function() {

  describe('LocationCtrl', function() {
    return it('tests stuff', function() {
      return expect(true).toBe(true);
    });
  });

}).call(this);
