// Generated by CoffeeScript 1.3.3
(function() {
  var app;

  app = angular.module('superhero', []);

  app.directive('superman', function() {
    return {
      restrict: 'E',
      template: "<div>Here I come to SAVE the day</div>"
    };
  });

}).call(this);
