// Generated by CoffeeScript 1.3.3
(function() {
  var app;

  app = angular.module('behaviorApp', []);

  app.directive('enter', function() {
    return function(scope, element) {
      return element.bind('mouseenter', function() {
        return console.log("I'm in side of you");
      });
    };
  });

  app.directive('leave', function() {
    return function(scope, element) {
      return element.bind('mouseleave', function() {
        return console.log("I left ya!");
      });
    };
  });

}).call(this);
